# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Menu:
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.resize(1024, 600)
        self.label_5 = QtWidgets.QLabel(Menu)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 200, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Menu)
        self.label_6.setGeometry(QtCore.QRect(272, 70, 480, 140))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName("label_6")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Menu)
        self.verticalLayoutWidget_3.setGeometry(
            QtCore.QRect(317, 200, 390, 261)
        )
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget_3
        )
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(12)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.world_width = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.world_width.setFont(font)
        self.world_width.setAlignment(QtCore.Qt.AlignCenter)
        self.world_width.setMinimum(1)
        self.world_width.setMaximum(100)
        self.world_width.setObjectName("world_width")
        self.horizontalLayout.addWidget(self.world_width)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.world_height = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.world_height.setFont(font)
        self.world_height.setAlignment(QtCore.Qt.AlignCenter)
        self.world_height.setMinimum(1)
        self.world_height.setMaximum(100)
        self.world_height.setObjectName("world_height")
        self.horizontalLayout_2.addWidget(self.world_height)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label.setMaximumSize(QtCore.QSize(16777215, 46))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.organisms_spin = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.organisms_spin.setFont(font)
        self.organisms_spin.setAlignment(QtCore.Qt.AlignCenter)
        self.organisms_spin.setMinimum(1)
        self.organisms_spin.setMaximum(1)
        self.organisms_spin.setObjectName("organisms_spin")
        self.verticalLayout.addWidget(self.organisms_spin)
        self.organisms_slider = QtWidgets.QSlider(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.organisms_slider.setFont(font)
        self.organisms_slider.setMinimum(1)
        self.organisms_slider.setMaximum(1)
        self.organisms_slider.setOrientation(QtCore.Qt.Horizontal)
        self.organisms_slider.setObjectName("organisms_slider")
        self.verticalLayout.addWidget(self.organisms_slider)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.start_button = QtWidgets.QPushButton(Menu)
        self.start_button.setGeometry(QtCore.QRect(437, 500, 150, 50))
        self.start_button.setMinimumSize(QtCore.QSize(0, 50))
        self.start_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.start_button.setFont(font)
        self.start_button.setFlat(False)
        self.start_button.setObjectName("start_button")

        self.retranslateUi(Menu)
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "Form"))
        self.label_5.setText(_translate("Menu", "Marcin Nadarzynski 184912"))
        self.label_6.setText(_translate("Menu", "Virtual World"))
        self.label_2.setText(_translate("Menu", "World size"))
        self.label_3.setText(_translate("Menu", "Width"))
        self.label_4.setText(_translate("Menu", "Height"))
        self.label.setText(_translate("Menu", "Number of organisms"))
        self.start_button.setText(_translate("Menu", "Start game"))
